# Generated by Django 5.0.2 on 2024-03-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('postage_type', models.CharField(choices=[('Standard', 'Standard'), ('Express', 'Express')], max_length=8)),
                ('full_name', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('suburb', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=10)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
