# Generated by Django 5.0.2 on 2024-03-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, unique=True)),
                ('total_debt', models.FloatField(default=0.0)),
                ('last_change', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('debt_increase', models.FloatField(default=0.0)),
                ('debt_decrease', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_payments', to='debtmanager.customer')),
                ('linked_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_payments', to='sales.sale')),
            ],
        ),
    ]
