# Generated by Django 5.0.2 on 2024-03-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('usage', 'Usage'), ('expense', 'Expense')], max_length=7)),
                ('value', models.FloatField()),
                ('loss', models.FloatField(editable=False)),
            ],
        ),
    ]
