# Generated by Django 5.0.2 on 2024-03-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField()),
                ('cost', models.FloatField()),
                ('supplier_debt', models.FloatField()),
                ('cost_price', models.FloatField(editable=False)),
            ],
            options={
                'db_table': 'reloads',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('profit', models.FloatField(default=0.0)),
                ('last_reload', models.DateTimeField(blank=True, null=True)),
                ('cost_price', models.FloatField(default=0.0)),
                ('total_supplier_debt', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'statistics',
            },
        ),
    ]
