# Generated by Django 5.0.2 on 2024-03-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('amount', models.FloatField()),
                ('profit', models.FloatField(editable=False)),
            ],
        ),
    ]
